### PR TITLE
Bugfix/rmk parsing

### LINKED ISSUE #329: RMK section of a TAF leading to bogus weather conditions
**Describe the bug**

I am noticing some bogus weather conditions being picked up from the RMK section of a TAF.

**To Reproduce**

1. Go to https://www.metar-taf-decoder.com/taf and input the following TAF (simplified to remove other trends, otherwise a valid TAF found in the wild):

```
TAF CYTL 121940Z 1220/1308
  TEMPO 1303/1308 2SM -SN RMK FCST BASED ON AUTO OBS. FCST BASED ON OBS BY OTHER SRCS. WIND SENSOR INOP. NXT FCST BY 130200Z
```

2. Notice funnel cloud weather conditions:

image

**Expected behavior**

No funnel cloud weather conditions.

**Additional context**

It appears to be picked up from the "remark" section. When I remove everything after `RMK` the problem goes away.

I believe the Python implementation has the same issue.

### PR DESCRIPTION
**Pull request by mivek**
fixes #329 

Added `break` statement after parsing remarks in the `updateTrend` method.
Added Turkish translation (thanks @[Suheyb](https://github.com/Suheyb))

### CODE REVIEW

File: metarParser-parsers/src/main/java/io/github/mivek/parser/AbstractTAFTrendParser.java [hunk 1]
```diff
@@ -36,6 +36,7 @@ void updateTrend(final int index, final String[] parts, final TafTrend trend) {
     for (int i = index; i < parts.length; i++) {
       if (RMK.equals(parts[i])) {
         parseRMK(trend, parts, i);
+        break;
```
Comment (aeharding) [inline metarParser-parsers/src/main/java/io/github/mivek/parser/AbstractTAFTrendParser.java:39]: Should there also be a `break;` after the RMK parsing of the TAF base (not trend) part? For example:

```
TAF CYTL 121940Z 1220/1308 RMK FCST BASED ON AUTO OBS. FCST BASED ON OBS BY OTHER SRCS. WIND SENSOR INOP. NXT FCST BY 130200Z
    TEMPO 1303/1308 2SM -SN
```
